apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gkka1efvj-python 
  janus-idp.io/tekton: gkka1efvj-python
  backstage.io/kubernetes-id: gkka1efvj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gkka1efvj-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  